---
title: "Project 2"
author: "Jeffrey Zhuohui Liang"
date: "3/24/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(MASS)
library(caret)
library(parallel)
library(foreach)
library(ggfortify)
library(patchwork)
library(cluster)
library(tidyverse)

knitr::opts_chunk$set(
  fig.height = 6,
  fig.width = 8,
  message = F,
  echo = T,
  warning = F,
  cache = F
)

theme_set(theme_minimal() + theme(legend.position = "bottom", 
                                  title = element_text(hjust = 0.5)))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
  digits = 3
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(123123)
```

```{r load_data, echo=F}
sngcll_raw = 
  read_csv("ss.csv") 

sngcll = sngcll_raw %>% 
  janitor::clean_names()
```

```{r eval=T}
pc = prcomp(sngcll, scale = F, center = T)
eigs = pc$sdev^2
summary.table = rbind(
  SD = sqrt(eigs),
  Proportion = eigs/sum(eigs),
  Cumulative = cumsum(eigs)/sum(eigs))
summary.table[,1:10] %>% 
  knitr::kable()
scores = pc$x
```


# Method

## Data Preparation

```{r standardize_data}
# drop gene that 90% is zero 
drop_gene = 
  sngcll %>% 
  summarise(across(everything(),~sum(.x==0)/n()<0.9)) %>% 
  slice(1) %>% 
  unlist() %>% 
  as.vector()

sngcll_dp0 = 
  sngcll[,drop_gene]
```

```{r pca}
# PCA with scale
sngcll_pca =
  #predict(preProcess(sngcll_dp0,c("center","scale","pca")),sngcll_dp0)
  prcomp( ~ .,
          data = sngcll_dp0,
          tol = sqrt(.Machine$double.eps),
          center =F,
          scale. = F,
          scale = F)

summary(sngcll_pca)$importance %>% 
  t() %>% 
  .[seq(1,230,8),] %>% 
  as_tibble(rownames = NA) %>% 
  knitr::kable(digits = 2)

sngcll_pca$rotation[,1:4] %>% t()%>% knitr::kable()
```

Using 90% as threshold for Principle component selection, we see that up to `r sum(summary(sngcll_pca)$importance[3,]<.9)` can explain 90% of the standard deviation in data.

```{r EM_data}
# EM data preparation
sngcll_pca =
  predict(preProcess(
    sngcll_dp0,
    c("pca","center","scale"),
    pcaComp = sum(summary(sngcll_pca)$importance[3, ]<.9)
  ), sngcll_dp0)
```


## Gaussian Mixture Model
```{r simulate_example echo = F}
mu1 = c(1,2,3)
sgm1 = diag(mu1)
mu2 = c(2,3,4)
sgm2 = diag(mu2)
mu3 = c(4,5,6)
sgm3 = diag(mu3)
mu = list(mu1,mu2,mu3)
sgm = list(sgm1,sgm2,sgm3)
cell = c(100,200,300)
sim_data = mclapply(X=1:3,
                    FUN = function(x){
                      MASS::mvrnorm(cell[[x]],
                                    mu[[x]],
                                    sgm[[x]])
                    },
                    mc.cores = 3) %>% 
  do.call(rbind,.)
```


```{r eval = F}
source("EM.R")

set.seed(123123)
rslt_2 = rerun(1,lapply(10:2, FUN = function(x) gaussian_mixture(sngcll_pca,x,method ="AIC")) %>% do.call(rbind,.)) %>% do.call(rbind,.)
save(rslt_2,file = "EM.Rdata")

set.seed(123123)
t1 = Sys.time()
rslt = rerun(20,lapply(10:2, FUN = function(x) gaussian_mixture(sngcll_pca,x,method ="AIC")) %>% do.call(rbind,.)) %>% do.call(rbind,.)
save(rslt,file = "EM_20.Rdata")
t_run = Sys.time() - t1
```


# Result

```{r plot}
load("EM.Rdata")

ggplot(as_tibble(rslt_2) %>% unnest(c(k, obj)), aes(k, obj)) +
  geom_path()+
  labs(y = "AIC")

sngcll_clu_3 = cbind(sngcll_pca,rslt_2[which(rslt_2[,"k"]==3),"cluster"])

pc2 = ggplot(sngcll_clu_3,aes(PC1,PC2,color = cluster))+geom_jitter(alpha = 0.8)

pc3 = ggplot(sngcll_clu_3,aes(PC1,PC3,color = cluster))+geom_jitter(alpha = 0.8)

pc4 = ggplot(sngcll_clu_3,aes(PC1,PC4,color = cluster))+geom_jitter(alpha = 0.8)

pc2 + pc3+pc4 +plot_spacer()+ plot_layout(nrow = 2,ncol = 2, guides = "collect")
```

